### DISCUSSION TITLE
Share your ideas ! 💡

### DISCUSSION THREAD

**Discussion by ugomeguerditchian** [ugomeguerditchian/OrgASM#3] [Ideas]
If anyone is interested in sharing new ideas to implement in OrgASM do not hesitate ! 🚀

**Comment by at0mman** [comment]
Can we have an option just for enum without vuln scan to make it quicker? Btw  really nice tool you guys have made, I use it regularly and like it.

**Reply by ugomeguerditchian** [reply]
Hi,

Thanks for your feedback ! 

If you want to just do the AS scan you can just disable all the "after_AS_scan" inside TOOLS section in your config file.

```yaml
TOOLS : 
     AS_scan: 
         brute_subs: 
             file: "brute_subs" 
             activate: true 
             workers: 3000 
             wordlist_name: "n0kovo_subdomains_tiny.txt" 
             resolver_name: "resolvers.txt" 
             recursive: true 
     after_AS_scan: 
         ports_scanner: 
             file: "ports_scanner" 
             activate: false
             workers: 2000 
         detect_services: 
             file: "detect_services" 
             activate: false
             workers: 2000     
         analyze_web_techno: 
             file: "analyze_web_techno" 
             activate: false
             workers: 2000 
         nuclei: 
             file: "nuclei" 
             headless_browser: false 
             activate: false
             conf_file: null
```

By doing this you will have the bruteforce enum and the querying of APIs in your result but not the others tools.

I think I will implement new args to make this quicker in the next version.

Do not hesitate if you have more questions !
