### ISSUE TITLE
Known issue : Getting FQDNs from certificates on huges scopes take a lot of fucking time

### ISSUE THREAD

**Issue by ugomeguerditchian** [ugomeguerditchian/OrgASM#5]
I will try to optimize this in next releases

If you want to avoid this you can disable it in the configuration file :

```yaml
FQDN :
    find_subs : True #will try to get subs when FQDN from ip is found
    get_fqdn_trough_proxy: False #will try to get fqdn trough proxy (All API)
    get_from_cert : False#connection to target will be made during initial scan    <---------- HERE
```
